print("enter two number:");
a=int(input("enter a value :"));
b=int(input("enter b value :"));
add=a+b;
sub=a-b;
mult=a*b;
divi=a/b;
mod=a%b;
print(add);
print(sub);
print(mult);
print(divi);
print(mod);
